spring.application.name=fitness-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_app
spring.datasource.username=mohammedzhairi
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true